### ISSUE TITLE
Blank page on setting page

### ISSUE THREAD

**Issue by Galixte** [rubencm/phpbb-ext-customregistrationagreement#3]
Hi @rubencm,

since the last modification in ```adm/style/acp_custom_registration_agreement.html``` file: https://github.com/rubencm/phpbb-ext-customregistrationagreement/commit/52a1bfe22f9c217c1ac07c64e1f4cfa51ebfb554 there is problem the setting page from this extension in EXTENSION tab is a blank page.

**Comment by rubencm** [comment]
Thanks, give me a few days and I will look at it when I'm home

**Comment by rubencm** [comment]
@Galixte Hello, i see why, is because twig function lang_defined() is only in branch 3.3.x.
So it should work in phpBB3.3.x, but not in phpBB3.2.x

**Comment by Galixte** [comment]
@rubencm Hi, phpBB 3.3.x isn’t released yet, so it’s a pity for users which currently used phpBB 3.2.x.

**Comment by rubencm** [comment]
Yes, but they shouldn't use this, they have the released version

**Comment by Galixte** [comment]
Ok. ;)
