### ISSUE TITLE
Crashing the Forum after amendment 

### ISSUE THREAD

**Issue by Acroxis** [rubencm/phpbb-ext-customregistrationagreement#4]
Having an issue with trying to substitute the relevant code with this amended line:
`'L_TERMS_OF_USE'	=> '</p>' . $register_agreement_message . '<p>',`

It is causing the board to crash - I have tried it 4 times now and can only get the Forum back up if I upload the original 'listener.php' file.  Of course that then still has the fault with not resetting the default paragraph style after a list code.

Can you just not provide the correct file already changed?  Thanks

**Comment by rubencm** [comment]
I don't understand

**Comment by Acroxis** [comment]
I've used another editor and it seems to be working now - something wasn't right, but fine now - thanks for the mod by the way.
